<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Twig_Extensions_' => array($vendorDir . '/twig/extensions/lib'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Stfalcon\\Bundle\\TinymceBundle' => array($vendorDir . '/stfalcon/tinymce-bundle'),
    'ProxyManager\\' => array($vendorDir . '/ocramius/proxy-manager/src'),
    'Metadata\\' => array($vendorDir . '/jms/metadata/src'),
    'Knp\\Component' => array($vendorDir . '/knplabs/knp-components/src'),
    'EightPoints\\Guzzle' => array($vendorDir . '/eightpoints/guzzle-wsse-middleware/src'),
    'EightPoints\\Bundle\\GuzzleBundle' => array($vendorDir . '/eightpoints/guzzle-bundle'),
    'Doctrine\\ORM\\' => array($vendorDir . '/doctrine/orm/lib'),
    'Doctrine\\DBAL\\' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'AlgoliaSearch' => array($vendorDir . '/algolia/algoliasearch-client-php/src'),
    'SendGrid' => array($vendorDir . '/sendgrid/php-http-client/lib'),
);
